#! /bin/bash

DIST=E1F3G8KJ19ONB9

# Seperate
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/media/*"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/media/CajunFest*"

# Do Together
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths /index.html /videomobile.html /publish-hashes.json 
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/assets/*"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths /index3.html "/assets/dan/*"

